<a href="https://colab.research.google.com/github/Ykulikova30157908643/Ucheba/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
kopilka = 0
month = 0
while kopilka < 1000000:
  kopilka = kopilka+10000
  month = month+1
print(month)

100

In [ ]:
for i in range(1, 10):
  print(i, end=" ")

1 3 5 7 9

In [ ]:
for x in range(1, 11):
  y=x**2
  print(y)

1
4
9
16
25
36
49
64
81
100

In [ ]:
A=[0, 1, 2, 3, 5, 6, 10, 13]

In [ ]:
print(A)

[0, 1, 2, 3, 5, 6, 10, 13]

In [ ]:
for i in range(len(A)):
  print (A[i])

0
1
2
3
5
6
10
13

In [ ]:
len(A)

8

In [ ]:
for i in range(len(A), 5):
  print (A[i])

In [ ]:
N=5
C=[0]*N
for i in range(N):
  C[i]=i**2
print(C)

[0, 1, 4, 9, 16]

In [ ]:
char='А'
unicode_value=ord(char)
print(unicode_value)

1040

In [ ]:
R={'PY5768':'New York','TY0492':'Moscow'}

In [ ]:
input('Введите ключ очередного элемента словаря')

Введите ключ очередного элемента словаря50

'50'

In [ ]:
import pandas as pd
my_series = pd.Series([5, 6, 7, 8, 9, 10])
print(my_series)

0     5
1     6
2     7
3     8
4     9
5    10
dtype: int64

In [ ]:
my_series[0:2]

0    5
1    6
dtype: int64

In [ ]:
my_series2 = pd.Series([5, 6, 7, 8, 9, 10], index=['a', 'b', 'c', 'd', 'e', 'f'])
my_series2['f']

10

In [ ]:
my_series2[['a','b','f']]

a     5
b     6
f    10
dtype: int64

In [ ]:
a = []
for i in range(0, 4):
  a.append(i*2+3)
my_series3 = pd.Series(a)
my_series3.index = ['Первый', 'Второй', 'Третий', 'Четвертый']
my_series3

Первый       3
Второй       5
Третий       7
Четвертый    9
dtype: int64

In [ ]:
data=pd.DataFrame([my_series,my_series*2,my_series*3])
data

    0   1   2   3   4   5
0   5   6   7   8   9  10
1  10  12  14  16  18  20
2  15  18  21  24  27  30

In [ ]:
dictionary = {'Name': ['Alice', 'Bob', 'Charlie'],
  'Age': [25, 30, 28],
  'City': ['New York', 'Los Angeles', 'Chicago']}
df = pd.DataFrame(dictionary)
df

      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   28      Chicago

In [ ]:
A=['Kazakhstan', 17.04, 2724902]
B=['Russia',  143.5, 17125191]
C=['Belarus', 9.5, 207600]
D=["country", "population", "square"]
data = pd.DataFrame(data = [A, B, C], columns=D)
data

      country  population    square
0  Kazakhstan       17.04   2724902
1      Russia      143.50  17125191
2     Belarus        9.50    207600

In [ ]:
data["country"]

0    Kazakhstan
1        Russia
2       Belarus
Name: country, dtype: object

In [ ]:
data[["country","population"]]

      country  population
0  Kazakhstan       17.04
1      Russia      143.50
2     Belarus        9.50

In [ ]:
data.loc[1]

country         Russia
population       143.5
square        17125191
Name: 1, dtype: object

In [ ]:
data.loc[data["country"] == "Russia"]

  country  population    square
1  Russia       143.5  17125191

In [ ]:
import pandas as pd
pd.read_csv("http://intersyn.net/Churn.csv")

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2.0,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1.0,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8.0,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1.0,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2.0,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5.0,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10.0,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7.0,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3.0,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,NaN,130142.79,1,1,0,38190.78,0

In [ ]:
data = pd.read_csv("http://intersyn.net/Churn.csv")
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2.0,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1.0,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8.0,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1.0,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2.0,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5.0,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10.0,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7.0,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3.0,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,NaN,130142.79,1,1,0,38190.78,0

In [ ]:
T=5
P=[]
for i in range(T):
  P.append(i**2)
print(P)

[0, 1, 4, 9, 16]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           9091 non-null   float64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(3), int64(8), object(3)
memory usage: 1.1+ MB

In [ ]:
data.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,9091.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,4.997690,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.894723,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,2.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [ ]:
df = pd.read_csv("shootings_USA.csv")

In [ ]:
df

,id,name,date,manner_of_death,armed,age,gender,race,city,state,signs_of_mental_illness,threat_level,flee,body_camera,arms_category,years_in_prison
0,3,Tim Elliot,2015-01-02,shot,gun,53.0,M,Asian,Shelton,WA,True,attack,Not fleeing,False,Guns,4
1,4,Lewis Lee Lembke,2015-01-02,shot,gun,47.0,M,White,Aloha,OR,False,attack,Not fleeing,False,Guns,20
2,5,John Paul Quintero,2015-01-03,shot and Tasered,unarmed,23.0,M,Hispanic,Wichita,KS,False,other,Not fleeing,False,Unarmed,0
3,8,Matthew Hoffman,2015-01-04,shot,toy weapon,32.0,M,White,San Francisco,CA,True,attack,Not fleeing,False,Other unusual objects,4
4,9,Michael Rodriguez,2015-01-04,shot,nail gun,39.0,M,Hispanic,Evans,CO,False,attack,Not fleeing,False,Piercing objects,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4840,5916,Rayshard Brooks,2020-06-12,shot,Taser,27.0,M,Black,Atlanta,GA,False,attack,Foot,True,Electrical devices,2
4841,5925,Caine Van Pelt,2020-06-12,shot,gun,23.0,M,Black,Crown Point,IN,False,attack,Car,False,Guns,3
4842,5918,Hannah Fizer,2020-06-13,shot,unarmed,25.0,F,White,Sedalia,MO,False,other,Not fleeing,False,Unarmed,1
4843,5921,William Slyter,2020-06-13,shot,gun,22.0,M,White,Kansas City,MO,False,other,Other,False,Guns,19
4844,5924,Nicholas Hirsh,2020-06-15,shot,gun,31.0,M,White,Lawrence,KS,False,attack,Car,False,Guns,7

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4845 entries, 0 to 4844
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       4845 non-null   int64
 1   name                     4845 non-null   object
 2   date                     4845 non-null   object
 3   manner_of_death          4845 non-null   object
 4   armed                    4845 non-null   object
 5   age                      4845 non-null   float64
 6   gender                   4845 non-null   object
 7   race                     4845 non-null   object
 8   city                     4845 non-null   object
 9   state                    4845 non-null   object
 10  signs_of_mental_illness  4845 non-null   bool
 11  threat_level             4845 non-null   object
 12  flee                     4845 non-null   object
 13  body_camera              4845 non-null   bool
 14  arms_category            4845 non-null   object
 15  years_in_prison          4845 non-null   int64
dtypes: bool(2), float64(1), int64(2), object(11)
memory usage: 539.5+ KB

In [ ]:
took = pd.read_excel("Russia.xlsx")

In [ ]:
took.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85 entries, 0 to 84
Data columns (total 11 columns):
 #   Column                                                                                                                        Non-Null Count  Dtype
---  ------                                                                                                                        --------------  -----
 0   Наименование                                                                                                                  85 non-null     object
 1   Средняя продолжительность жизни ЖЕНЩИН                                                                                        85 non-null     float64
 2   Младенческая смертность, число детей, умерших в возрасте до 1 года, на 1000 родившихся живыми                                85 non-null     float64
 3   Заболеваемость на 1000 человек населения                                                                                      85 non-null     float64
 4   Численность населения на одну больничную койку                                                                                85 non-null     float64
 5   Уровень безработицы населения в возрасте 15-72 лет, %                                                                         85 non-null     float64
 6   Численность студентов, обучающихся по программам бакалавриата, специалитета, магистратуры на 10 000 человек населения, всего  85 non-null     int64
 7   Среднемесячная номинальная начисленная заработная плата работников организаций, руб.                                         85 non-null     int64
 8   Кол-во преступлений (наркотики) на 1000 человек                                                                               85 non-null     float64
 9   Кол-во преступлений экономической направленности на 1000 человек                                                              85 non-null     float64
 10  Выявлено лиц, совершивших преступления в состоянии алкогольного опьянения на 1000 человек                                     85 non-null     float64
dtypes: float64(8), int64(2), object(1)
memory usage: 7.4+ KB

In [ ]:
took.describe()

,Средняя продолжительность жизни ЖЕНЩИН,"Младенческая смертность, число детей, умерших в возрасте до 1 года, на 1000 родившихся живыми",Заболеваемость на 1000 человек населения,Численность населения на одну больничную койку,"Уровень безработицы населения в возрасте 15-72 лет, %","Численность студентов, обучающихся по программам бакалавриата, специалитета, магистратуры на 10 000 человек населения, всего","Среднемесячная номинальная начисленная заработная плата работников организаций, руб.",Кол-во преступлений (наркотики) на 1000 человек,Кол-во преступлений экономической направленности на 1000 человек,"Выявлено лиц, совершивших преступления в состоянии алкогольного опьянения на 1000 человек"
count,85.000000,85.000000,85.000000,85.000000,85.000000,85.000000,85.000000,85.000000,85.000000,85.000000
mean,76.038824,4.709412,765.257647,121.202353,7.031765,231.694118,45716.729412,0.684317,0.678219,2.430254
std,1.899839,1.580131,157.562374,18.548732,4.098293,102.882390,20158.539002,0.368162,0.311877,1.302227
min,68.810000,2.100000,309.000000,77.600000,2.400000,7.000000,29083.000000,0.119259,0.245044,0.100086
25%,75.270000,3.700000,665.400000,110.000000,4.900000,172.000000,33139.000000,0.421079,0.509249,1.628944
50%,75.940000,4.400000,748.800000,120.800000,5.900000,230.000000,37820.000000,0.610335,0.628480,2.224328
75%,76.890000,5.500000,845.700000,129.700000,7.700000,285.000000,48286.000000,0.838700,0.756607,3.094102
max,84.610000,14.700000,1249.400000,205.300000,30.000000,577.000000,120641.000000,1.909117,2.711701,6.310651

In [ ]:
yt = pd.read_json("EmployeeData.json")
yt

,id,name,email,password,about,token,country,location,lng,lat,...,sendmenotifications,sendTextmessages,enabletagging,createdAt,updatedAt,livelng,livelat,liveLocation,creditBalance,myCash
0,4051,manoj,manoj@gmail.com,Test@123,None,7f471974-ae46-4ac0-a882-1980c300c4d6,NaN,None,0.0000,0.000000,...,False,False,False,2020-01-01T11:13:27.1107739,2020-01-02T09:16:49.284864,77.389849,28.628223,"Unnamed Road, Chhijarsi, Sector 63, Noida, Utt...",127,0
1,4050,pankaj,p1@gmail.com,Test@123,None,e269eeef-1de1-4438-885a-e30a9ad26106,NaN,None,0.0000,0.000000,...,False,False,False,2020-01-01T07:39:34.1618239,2020-01-01T07:39:34.161824,0.000000,0.000000,None,0,0
2,3050,Neeraj1993,neeraj.singh@adequateinfosoft.com,286956,None,562c2fb5-6799-4b51-8733-a60564c96adc,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-27T10:16:05.6578091,2019-12-27T10:22:30.8416992,77.389849,28.628223,"Unnamed Road, Chhijarsi, Sector 63, Noida, Utt...",0,0
3,3049,Sophia,sophia@gmail.com,Test@123,Yo,f3bc9393-ad13-41a2-a69b-b607a42d829f,NaN,"18302 Lorance Trail, Little Rock, AR 72206, USA",0.0000,0.000000,...,False,False,False,2019-12-26T07:36:22.3481221,2019-12-26T07:36:22.3481222,77.367424,28.626067,"35, Block A, Industrial Area, Sector 62, Noida...",36,0
4,3048,Raju Prasad,raju.nsit@gmail.com,Raju@1234,Don't Quit Your Day Dream,b3eda104-0771-4804-8be2-0e6d7c16412d,NaN,"Karbala Rd, Block G, Sector 5, Dakshinpuri, Ne...",0.0000,0.000000,...,True,True,True,2019-12-26T07:17:08.3460039,2019-12-26T14:27:00.4327446,77.367424,28.626067,"35, Block A, Industrial Area, Sector 62, Noida...",5,0
5,3047,Ankiish Thapliyal,thapliyalankiish958@gmail.com,Test@1234,I failed many opportunities may times but I am...,caf070df-d2c2-4e99-ba06-9482ef5eb7ba,NaN,Dehradun,0.0000,0.000000,...,True,True,True,2019-12-26T07:13:01.9262534,2019-12-30T11:11:00.4082038,77.379004,28.630186,"Suite No. 203 H - 15 Rise tower, Sector 63, H ...",167,0
6,3046,Aryan Thapliyal,ashithewarrior@gmail.com,Test@1234,Testing is required for an effective performan...,c8cb5636-cd01-4133-adac-360cecc710af,NaN,Dehradun,0.0000,0.000000,...,False,False,False,2019-12-26T07:10:53.2318238,2019-12-30T05:32:04.0700419,77.379012,28.630237,"H15, H Block, Sector 63, Noida, Uttar Pradesh ...",160,0
7,3045,shivam,shivam@gmail.com,Shivam@123,None,59b6f0af-fc25-4a6b-b865-5fb29023c6df,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-26T07:01:24.5014557,2019-12-26T07:02:16.9663295,77.367424,28.626067,"35, Block A, Industrial Area, Sector 62, Noida...",11,0
8,3044,Navya Upadhyay,navya.adequate@gmail.com,navya2123,None,0362f1b5-80be-4dff-bd40-c236c79561eb,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-26T06:53:22.1076016,2019-12-26T06:53:22.1076017,0.000000,0.000000,None,5,0
9,3043,Ritu singh,ritusinghadequate@gmail.com,ritusingh1234,None,a268517f-960a-418a-9c89-48708372702d,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-26T06:53:10.2343196,2019-12-26T06:53:10.2343197,0.000000,0.000000,None,5,0
10,3042,faiz,faizadequate@gmail.com,Test@1234,I am who I am. Your approval is not needed.,33dd5829-0a01-4b3b-80d3-1a63a75b3436,NaN,New Delhi,0.0000,0.000000,...,False,False,False,2019-12-26T06:30:58.6524884,2019-12-30T06:57:19.58494,77.379012,28.630232,"H15, H Block, Sector 63, Noida, Uttar Pradesh ...",38,0
11,3041,Martin Wilson,ravencomputer667@gmail.com,martin@123,"Travelers,",18ceb759-241c-43d3-a9eb-5344ea2ef1d9,NaN,"Moorgate Station (Stop N), London EC2Y 5EJ, UK",0.0000,0.000000,...,True,False,False,2019-12-26T06:22:36.1180762,2019-12-26T06:29:14.6591852,0.000000,0.000000,None,18,0
12,3040,Shweta Singh,amelia.claire.hi@gmail.com,Test@1234,What others think of me is none of my business...,e32b4e12-18f3-4fd0-9a3d-2021d8381dff,NaN,"India - Pakistan Border Rd, Bakhasar, Rajastha...",0.0000,0.000000,...,False,False,False,2019-12-26T06:20:51.0353245,2019-12-30T06:24:31.9803752,77.379004,28.630206,"Suite No. 203 H - 15 Rise tower, Sector 63, H ...",77,0
13,3039,jagjit,jagjit.singh.adequate.36@gmail.com,Test@1234,Take a chance and live life to the fullest. Wh...,1e150816-7075-4d6d-b3d6-eb1c0e415e61,NaN,"Delhi - Meerut Expy, Nai Basti Dundahera, Ghaz...",0.0000,0.000000,...,False,False,False,2019-12-26T06:20:32.873132,2020-01-02T06:29:36.6383214,77.379012,28.630190,"H15, H Block, Sector 63, Noida, Uttar Pradesh ...",32,0
14,3038,Ashi 123,ashi123@gmail.com,Test@1234,None,61a43ad3-02b3-4431-8c1b-1d29933147e1,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-26T05:30:27.4225101,2019-12-26T05:30:27.4225102,0.000000,0.000000,None,0,0
15,3037,shivamvermaa4,shivam.vemaa4@gmail.com,Shivam@123,None,97534ce9-5386-4b92-9741-fc1860bbcd1a,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-24T11:58:30.3613651,2019-12-24T11:58:30.3613651,77.389849,28.628223,"Unnamed Road, Chhijarsi, Sector 63, Noida, Utt...",10,0
16,3036,Sophia,n2@gmail.com,Test@123,WE,1ebfb0ac-7d98-43fb-ba41-0e40091c6071,NaN,"Saint-Louis-Strasse 3, 4056 Basel, Switzerland",0.0000,0.000000,...,False,False,False,2019-12-24T11:36:36.1739424,2019-12-26T09:48:57.2586835,77.389849,28.628223,"Unnamed Road, Chhijarsi, Sector 63, Noida, Utt...",45,0
17,3035,n1,n1@gmail.com,Test@123,An ordinary Bharitya,c40422ef-27ac-4e40-adf5-87403143dc99,NaN,451 DERA THAKRAN HARIDWAR ROAD MAHANT BALBIR S...,0.0000,0.000000,...,False,False,False,2019-12-24T11:36:03.4815197,2020-01-02T07:20:34.2742376,77.389849,28.628223,"Unnamed Road, Chhijarsi, Sector 63, Noida, Utt...",187,0
18,3034,neha,neha@gmail.com,Test@123,None,6aaaa999-8e14-40ca-b043-087624c48fd1,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-24T10:35:00.1292083,2019-12-24T10:35:00.1292083,77.367424,28.626067,"35, Block A, Industrial Area, Sector 62, Noida...",53,0
19,3033,sanjay,sanjay@gmail.com,Test@123,None,c9989beb-685a-41d7-b6de-77dd208979df,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-24T08:16:23.8466413,2019-12-24T08:16:23.8466414,77.367424,28.626067,"35, Block A, Industrial Area, Sector 62, Noida...",81,0
20,3032,Akku2,akku2@gmail.com,zxcvbnm1,None,12ac2112-c7b3-47d3-8d48-e839a1ce3955,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-24T07:30:32.9445148,2019-12-24T07:30:32.9445148,77.379047,28.630220,"H15, H Block, Sector 63, Noida, Uttar Pradesh ...",0,0
21,3031,Ashish Thapliyal,ashi1@gmail.com,Test@1234,"I Am Who I Am, Your Approval Is Not Needed. I ...",8889db9b-01f6-4305-b07d-aecc516037bb,NaN,"NH34, Shatabdi Nagar, Rithani, Meerut, Uttar P...",0.0000,0.000000,...,True,True,True,2019-12-24T06:52:08.6757278,2020-01-02T06:30:51.6595305,77.379017,28.630194,"H15, H Block, Sector 63, Noida, Uttar Pradesh ...",206,0
22,3030,singh,singh@gmail.com,Test@123,jdfgjghjgf,280a1f00-8597-4eee-8d46-9c8d5a120ac7,NaN,"Jg Halli Rd, Karnataka 577533, India",0.0000,0.000000,...,False,False,False,2019-12-24T06:32:23.0727945,2019-12-24T09:39:40.1944746,77.389824,28.628582,"noidya sector 63 Vidya polymer, Chhijarsi, Sec...",30,0
23,3029,Akku Testing,akku1@gmail.com,zxcvbnm1,"For some reason you've got ""bootstrap-sass"": ""...",7b0400eb-cd4f-45df-a8db-0c0871d46906,NaN,"Noida-Greater Noida Expressway, Amit Nagar, Sa...",0.0000,0.000000,...,True,True,False,2019-12-24T06:31:54.9038705,2019-12-24T13:00:12.9520741,77.379025,28.630216,"H15, H Block, Sector 63, Noida, Uttar Pradesh ...",161,0
24,3028,Aakankshi Gupta,aakankshi.cuminte@gmail.com,116331365713184193775,None,c916c01f-5844-445b-9f5a-e60d77ecb620,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-16T06:56:43.320768,2019-12-16T06:56:43.3207681,77.379024,28.630210,"H15, H Block, Sector 63, Noida, Uttar Pradesh ...",0,0
25,3026,Manresh Chandra 5,manresh5@gmail.com,zxcvbnm1,about.me is a personal web hosting service co-...,3c8ad706-9667-477a-adb6-3539f7b10a67,NaN,Deák Ferenc tér,0.0000,0.000000,...,True,True,False,2019-12-16T05:13:28.5717641,2019-12-16T05:13:28.5717641,77.379034,28.630178,"H15, H Block, Sector 63, Noida, Uttar Pradesh ...",0,0
26,3025,Manresh Chandra 4,manresh4@gmail.com,zxcvbnm1,None,8131e59d-7c83-4024-9423-0639a5887b52,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-16T05:11:34.473505,2019-12-16T05:11:34.473505,0.000000,0.000000,None,0,0
27,3024,Manresh Chandra 3,manresh3@gmail.com,zxcvbnm1,None,dc752b59-3d36-4b07-bc5c-6cd5913bae83,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-16T05:03:39.4564421,2019-12-16T05:03:39.4564423,0.000000,0.000000,None,3,0
28,3023,Manresh Chandra 2,manresh2@gmail.com,zxcvbnm1,None,867f49f2-8af8-45bf-9bd5-28ec641d3c44,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-16T05:01:14.0246654,2019-12-16T05:01:14.0246654,0.000000,0.000000,None,0,0
29,3022,Raju Prasad,raju.prasad@adequateinfosoft.com,Raju@1234,None,58ecfd42-7f10-440e-8007-29c6fa524040,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-13T14:36:34.2151655,2019-12-13T14:36:34.2151655,0.000000,0.000000,None,0,0
30,3021,Ashok Patel,ashoktest@gmail.com,ashokpatel457,None,520302ff-b08d-445f-be70-11c02d257e7e,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-13T13:47:59.4288322,2019-12-13T13:47:59.4288322,0.000000,0.000000,None,3,0
31,2021,manresh1,manresh1@gmail.com,zxcvbnm1,None,9305e1c5-82e2-4a79-b0ca-37bb5880f505,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-13T13:17:31.2904215,2019-12-13T13:17:31.2904216,0.000000,0.000000,None,2,0
32,2020,Manresh Chandra,manresh@gmail.com,zxcvbnm1,My Name is Manresh Chandra. I'm self Motivated...,bc370f5f-7d13-4fe6-9c2c-848198394f8a,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-13T07:08:47.9644619,2019-12-13T07:08:47.9644619,0.000000,0.000000,None,3,0
33,2019,Test,aakankshi7@gmail.com,zxcvbnm1,test,5a1218d2-5d66-4255-9137-0f7e700bdcab,NaN,Noida,0.0000,0.000000,...,False,False,False,2019-12-05T05:39:51.4928759,2019-12-05T06:41:24.107938,0.000000,0.000000,None,2,0
34,2018,aakankshi6,aakankshi6@gmail.com,zxcvbnm1,A traveller without observation is a bird with...,0ab8257f-7574-476d-b96f-508d3917af9b,NaN,Noida,0.0000,0.000000,...,False,False,False,2019-12-05T05:16:04.4212331,2019-12-05T12:25:13.6221215,0.000000,0.000000,None,0,0
35,2017,aakankshi5,aakankshi5@gmail.com,zxcvbnm1,None,b6fcf970-3271-492b-866c-76238f126c3f,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-05T05:06:49.1838089,2019-12-05T05:22:00.9403881,0.000000,0.000000,None,1,0
36,2016,aakankshi4,aakankshi4@gmail.com,zxcvbnm1,None,1b43db89-29a4-4966-ae57-86d705978dd3,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-05T05:04:21.8383669,2019-12-05T05:21:57.4139934,0.000000,0.000000,None,0,0
37,2015,aakankshi3,aakankshi3@gmail.com,zxcvbnm1,None,d65f85e3-0f8d-4c67-8de8-1546a7518cba,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-05T05:02:05.1655627,2019-12-05T05:21:54.2379269,0.000000,0.000000,None,0,0
38,2014,Aakankshi 2,aakankshi2@gmail.com,zxcvbnm1,ewewrewrew,4e2923a9-b059-4dc9-8d92-ce0cffa84208,NaN,Dada Dev Mandir Road,0.0000,0.000000,...,True,True,False,2019-12-05T05:00:19.5034062,2019-12-05T05:00:19.5034063,77.379025,28.630214,"H15, H Block, Sector 63, Noida, Uttar Pradesh ...",5,0
39,2013,Aakankshi 1,aakankshi1@gmail.com,zxcvbnm1,foundations in psychology and sociology and st...,d7fa7194-5ac2-4e32-b11b-3792e5cc067c,NaN,Delhi,0.0000,0.000000,...,True,True,True,2019-12-05T04:38:32.7808454,2019-12-06T05:41:05.3597939,77.389849,28.628223,"Unnamed Road, Chhijarsi, Sector 63, Noida, Utt...",269,36
40,2012,Aakankshi Gupta,aakankshi@gmail.com,zxcvbnm1,None,4c02ee6e-2cb5-4b75-888f-4adb7c790dad,NaN,None,0.0000,0.000000,...,False,False,False,2019-12-05T04:35:42.6189131,2019-12-05T04:35:42.6189131,0.000000,0.000000,None,3,0
41,2011,Aankashi,alokpatel@gmail.com,pankaj@123,its me,4516169a-58e3-4d04-a355-8c608be5d583,NaN,New Delhi,0.0000,0.000000,...,False,False,False,2019-11-30T05:36:52.1332523,2019-12-05T05:21:49.0948144,0.000000,0.000000,None,4,0
42,2010,Test 10,test02@gmail.com,123456,None,ba805b5d-f38f-4a33-9fcb-60f30923479d,NaN,None,0.0000,0.000000,...,False,False,False,2019-11-27T10:41:07.8215121,2019-11-27T10:41:07.8215122,0.000000,0.000000,None,3,0
43,2009,Test 9,test10@gmail.com,123456,None,1fa26ffa-465e-499f-ae9d-3e36fb94a0ea,NaN,None,0.0000,0.000000,...,False,False,False,2019-11-27T10:20:10.5816545,2019-11-27T10:20:10.5816545,0.000000,0.000000,None,0,0
44,2008,Test 8,test3@test.com,123456,None,822e8f5c-74ba-41f9-911e-9e5a47351dc5,NaN,None,0.0000,0.000000,...,False,False,False,2019-11-27T10:09:42.6969868,2019-11-27T10:09:42.6969869,0.000000,0.000000,None,0,0
45,2007,Neeraj Singh,neirajsingh100@gmail.com,100569704678350206382,None,47d25887-1933-4cbc-a4eb-6cc829c9cad6,NaN,None,0.0000,0.000000,...,False,False,False,2019-11-26T12:42:18.6778716,2019-12-05T05:20:40.9827126,0.000000,0.000000,None,2,0
46,2006,Hr. Niels Henriksen,contact@adequateinfosoft.com,354343138574152,i am software developer,347d684e-da9b-450e-bc94-cd5a99b04234,NaN,"Jaypee Greens Pari Chowk, Tugalpur Village, Gr...",0.0000,0.000000,...,False,False,False,2019-11-26T05:58:34.894975,2019-12-05T05:20:37.5393081,77.379024,28.630209,"H15, H Block, Sector 63, Noida, Uttar Pradesh ...",11,0
47,2005,Test 6,pankajadequate@gmail.com,sndsjkdsaj161564sasa,None,7a4ae2e1-5b65-4aad-96f0-43336fad5a3b,NaN,None,0.0000,0.000000,...,False,False,False,2019-11-25T13:12:47.6690112,2019-12-05T05:20:34.2935856,0.000000,0.000000,None,2,0
48,2004,Test 5,pankajws@gmail.com,Pankaj@123,None,1fd08288-57aa-41d9-ae44-29fcbb0a78a6,NaN,None,0.0000,0.000000,...,False,False,False,2019-11-25T11:29:06.938541,2019-12-05T05:20:30.604524,0.000000,0.000000,None,4,0
49,2,rajat Saxena,rajat.nirmal@gmail.com,test,abcd,00fb57db-10ad-4661-b3e0-7366c6698ac0,NaN,3465,8.7977,5.834876,...,False,False,False,2019-11-17T16:56:35.8,2019-12-05T05:21:02.1337931,0.000000,0.000000,None,43,0
50,3,Pankaj Patel,Pankaj@gmail.com,123456,None,f6b4bcc8-448b-4b65-84cb-48e9569c5cfe,NaN,None,0.0000,0.000000,...,False,False,False,0001-01-01T00:00:00,2019-12-05T13:25:01.977078,0.000000,0.000000,None,62,0
51,1003,Test 2,pankajabc@gmail.com,Pankaj@123,An ordinary bhartiya..,c8f53478-4cfb-4382-8531-b44b6d20cd8c,NaN,"Jaipur Engineering College Rd, Kukas, Rajastha...",0.0000,0.000000,...,False,False,False,0001-01-01T00:00:00,2019-12-23T13:43:27.5816869,77.389849,28.628223,"Unnamed Road, Chhijarsi, Sector 63, Noida, Utt...",16,0
52,1004,Test 2,pankajabcd@gmail.com,Pankaj@123,None,3f92cdef-1d8a-4f08-8468-9938dc9284ce,NaN,None,0.0000,0.000000,...,False,False,False,0001-01-01T00:00:00,2019-12-05T05:19:23.3650433,77.367424,28.626067,"35, Block A, Industrial Area, Sector 62, Noida...",3,0
53,1005,Test 3,test@test.com,123456,None,cc2ed6c5-0a59-4aca-9b8e-a686e0a4fa03,NaN,None,0.0000,0.000000,...,False,False,False,0001-01-01T00:00:00,2019-12-05T05:19:29.704463,0.000000,0.000000,None,44,0
54,1006,Test 4,test1@test.com,123456,None,f33f3325-bb08-41a5-b545-d2b5c443720f,NaN,None,0.0000,0.000000,...,False,False,False,0001-01-01T00:00:00,2019-12-05T05:22:11.8963884,0.000000,0.000000,None,1,0

In [ ]:
yt.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   55 non-null     int64
 1   name                 55 non-null     object
 2   email                55 non-null     object
 3   password             55 non-null     object
 4   about                23 non-null     object
 5   token                55 non-null     object
 6   country              0 non-null      float64
 7   location             22 non-null     object
 8   lng                  55 non-null     float64
 9   lat                  55 non-null     float64
 10  dob                  22 non-null     object
 11  gender               55 non-null     int64
 12  userType             55 non-null     int64
 13  userStatus           55 non-null     int64
 14  profilePicture       25 non-null     object
 15  coverPicture         30 non-null     object
 16  enablefollowme       55 non-null     bool
 17  sendmenotifications  55 non-null     bool
 18  sendTextmessages     55 non-null     bool
 19  enabletagging        55 non-null     bool
 20  createdAt            55 non-null     object
 21  updatedAt            55 non-null     object
 22  livelng              55 non-null     float64
 23  livelat              55 non-null     float64
 24  liveLocation         26 non-null     object
 25  creditBalance        55 non-null     int64
 26  myCash               55 non-null     int64
dtypes: bool(4), float64(5), int64(6), object(12)
memory usage: 10.2+ KB

In [ ]:
yt.describe()

,id,country,lng,lat,gender,userType,userStatus,livelng,livelat,creditBalance,myCash
count,55.000000,0.0,55.000000,55.000000,55.000000,55.0,55.0,55.000000,55.000000,55.000000,55.000000
mean,2479.763636,NaN,0.159958,0.106089,0.545455,1.0,1.0,36.579483,13.533546,35.272727,0.654545
std,847.789063,NaN,1.186282,0.786775,0.812362,0.0,0.0,38.988305,14.424753,62.006408,4.854239
min,2.000000,NaN,0.000000,0.000000,0.000000,1.0,1.0,0.000000,0.000000,0.000000,0.000000
25%,2011.500000,NaN,0.000000,0.000000,0.000000,1.0,1.0,0.000000,0.000000,0.500000,0.000000
50%,3024.000000,NaN,0.000000,0.000000,0.000000,1.0,1.0,0.000000,0.000000,4.000000,0.000000
75%,3038.500000,NaN,0.000000,0.000000,1.000000,1.0,1.0,77.379020,28.628223,40.500000,0.000000
max,4051.000000,NaN,8.797700,5.834876,3.000000,1.0,1.0,77.389849,28.630237,269.000000,36.000000

In [4]:
import pandas as pd
df = pd.DataFrame({'x':[1,3,2], 'y':[2,4,1]})
df

   x  y
0  1  2
1  3  4
2  2  1

In [7]:
df.drop(1, axis=0, inplace=True)
df

   y
0  2
2  1

In [8]:
df1 = pd.DataFrame({'x':[1,3,2], 'y':[2,4,1]})
df2 = pd.DataFrame({'x':[3,1,2], 'y':[0,2,2]})
print (df1>=df2)

       x      y
0  False   True
1   True   True
2   True  False